### ISSUE TITLE
Our Rockets part's pointer can be cursor and in contact us section more options can be added

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [Jagroop2001/AcmeRockets#1]

**Comment by Jagroop2001** [comment]
Hello, @Ishitamukherjee2004  This issue will be assigned to you as soon as the contribution period begins. However, you can work on this till then.

**Comment by vishal2005025** [comment]
I have read the issue and I am eagerly want to contribute in this issue .
please assign it to me under JWOC'2024.
