### ISSUE TITLE
Add Navbar & Footer to the other pages

### ISSUE THREAD

**Issue by Surajit0573** [Jagroop2001/AcmeRockets#101]
I want to Add Navbar & Footer to the ...
- Rate Us page
- Contributor page
- Feedback page

to match the UI of this pages to the landing page.

Assign me under JWOC 2024, if approved.

![image](https://github.com/Jagroop2001/AcmeRockets/assets/111490250/40572ff1-64e4-41da-80b6-bcc66670b7de)
![image](https://github.com/Jagroop2001/AcmeRockets/assets/111490250/8ae10fdc-c975-4e72-8877-2be50382bdf8)
![image](https://github.com/Jagroop2001/AcmeRockets/assets/111490250/749e55af-f848-4dc6-80a0-e6c95bb8d71c)

**Comment by Jagroop2001** [comment]
@Surajit0573 , go for it.

**Comment by Surajit0573** [comment]
@Jagroop2001, Please Review my PR
