### ISSUE TITLE
Adding icon

### ISSUE THREAD

**Issue by MaruthiSingh** [Jagroop2001/AcmeRockets#12]
New Update -
Adding icon

Expected output-
![image](https://github.com/Jagroop2001/AcmeRockets/assets/103304179/aff84a46-4fc5-41ec-b006-772d07c7954e)

**Comment by Jagroop2001** [comment]
You mean favicon !!
@MaruthiSingh , go for it.

**Comment by MaruthiSingh** [comment]
@Jagroop2001  Created a pull request can you merge so I can work on issue#13

**Comment by Jagroop2001** [comment]
@MaruthiSingh , please check comments on the PR

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/pull/14
