### ISSUE TITLE
Creating a google sheet backend

### ISSUE THREAD

**Issue by MaruthiSingh** [Jagroop2001/AcmeRockets#13]
New Update -
Connecting the contact us form with google sheet as backend

This is the output I have been working on -

https://github.com/Jagroop2001/AcmeRockets/assets/103304179/2b48a22f-1c70-47b2-9eb9-e74fc20151be

Here the google sheet url - https://docs.google.com/spreadsheets/d/10R_q-3XfTFBexM53z6-_86F7YqiIHKh0b87bWgbCIrw/edit?usp=sharing

**Comment by Jagroop2001** [comment]
@MaruthiSingh ,
You can now work on this.

**Comment by MaruthiSingh** [comment]
Hey @Jagroop2001 , what message should I keep after he submits the form?

**Comment by Jagroop2001** [comment]
@MaruthiSingh , message in the video looks good. I will review that PR.

**Comment by MaruthiSingh** [comment]
@Jagroop2001 Did you check the PR?
