### ISSUE TITLE
Converting Testimonials Section into slider 

### ISSUE THREAD

**Issue by nandita27iitp** [Jagroop2001/AcmeRockets#17]
@Jagroop2001 Pls assign this issue under jwoc

**Comment by Jagroop2001** [comment]
@nandita27iitp , go for it.

**Comment by nandita27iitp** [comment]
![image](https://github.com/Jagroop2001/AcmeRockets/assets/94813932/89005b3d-5f6b-4c96-85ba-b3bb29ba4d82)
![image](https://github.com/Jagroop2001/AcmeRockets/assets/94813932/48a812f8-1b9a-4101-8ad7-b3c09fcdf503)

@Jagroop2001 pls review it

**Comment by nandita27iitp** [comment]
@Jagroop2001

**Comment by Jagroop2001** [comment]
@nandita27iitp , good !!
Please add a PR.

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/pull/34
