### ISSUE TITLE
Footer Section Enhancement: Improved Navigation and Visual Appeal

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [Jagroop2001/AcmeRockets#2]
Evaluate and streamline the existing footer navigation links for better clarity and ease of access. Ensure that the links are organized logically to enhance the user experience.
Consider adding relevant links to important pages or resources, such as FAQs, Terms of Service, or a Site Map. This can provide users with quick access to essential information. please assign me this under JWoC

**Comment by Jagroop2001** [comment]
Hello, @NaveenChandraAdhikari  This issue will be assigned to you as soon as the contribution period begins. However, you can work on this till then.
