### ISSUE TITLE
improving the nav bar 

### ISSUE THREAD

**Issue by smritig26** [Jagroop2001/AcmeRockets#20]
adding advanced hover effects on nav bar. Please assign me this issue under jwoc

**Comment by Jagroop2001** [comment]
@smritig26 , go for it.

**Comment by vishal2005025** [comment]
Hi, I have read the issue and I am eagerly interested to contribute in this issue .
please assign it to me under JWOC'2024.

**Comment by Jagroop2001** [comment]
@smritig26 , please reply are you still working. If i didn't get any reply  within 12 hrs I will assign this to @vishal2005025

**Comment by smritig26** [comment]
yes i have made a pull request too

**Comment by Jagroop2001** [comment]
@smritig26 , where is your PR. I didn't see in the list.

**Comment by smritig26** [comment]
i am facing some issue in raising the PR. please give me some time i'll
make a pull request. I have already worked on the issue
