### ISSUE TITLE
Correct github link for issue tracket

### ISSUE THREAD

**Issue by Jagroop2001** [Jagroop2001/AcmeRockets#25]
In the readme.md file , in the Issue **Tracker Section** , please correct the link to : 
https://github.com/Jagroop2001/AcmeRockets/issues

**Comment by debuuuu007** [comment]
I would like to do it under jwoc'24.

**Comment by Jenis07** [comment]
Can you Please assign me this issue under JWOC?

**Comment by Jagroop2001** [comment]
@debuuuu007 , go for it.

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/pull/29
