### ISSUE TITLE
Add code of conduct and  MIT Liscence Page.

### ISSUE THREAD

**Issue by Jagroop2001** [Jagroop2001/AcmeRockets#26]

**Comment by manyaa1** [comment]
hey @Jagroop2001 assign me this issue.
Also, I wanted to know where do you want these to be added.

**Comment by Jagroop2001** [comment]
@manya1 , go for it .

**Comment by manyaa1** [comment]
@Jagroop2001 could you please provide me with code of conduct link as it gets broken and this has been coming up-
The master branch of AcmeRockets does not contain the path CODE_OF_CONDUCT.md.

**Comment by Jagroop2001** [comment]
You can create that in this project. Currently it's not available. That's why it's get broken.

**Comment by manyaa1** [comment]
<img width="863" alt="mit" src="https://github.com/Jagroop2001/AcmeRockets/assets/134845162/9fe222a4-9273-4bfd-a8a3-52c363f4a7b5">
Hey @Jagroop2001 please give feedback about what modifications do I need to make

**Comment by Jagroop2001** [comment]
Good to go @manyaa1  !!

**Comment by manyaa1** [comment]
<img width="485" alt="image" src="https://github.com/Jagroop2001/AcmeRockets/assets/134845162/e134a690-234f-48f7-a537-ab4462f3db4d">
@Jagroop2001 is this is okay?

**Comment by Jagroop2001** [comment]
@manyaa1 , you have to add in github links as well like here :  
![Screenshot from 2024-01-22 10-13-38](https://github.com/Jagroop2001/AcmeRockets/assets/99062463/d086aa25-4bae-4a04-9ce5-0c0734e4976c)

Currently it is not working.
You can add this in code as well. I will change the tag to Hard

**Comment by manyaa1** [comment]
<img width="529" alt="image" src="https://github.com/Jagroop2001/AcmeRockets/assets/134845162/3bc92b1b-b1ab-4ccd-9d17-d098639e8114"
<img width="185" alt="image" src="https://github.com/Jagroop2001/AcmeRockets/assets/134845162/cbfc0d5c-0d6e-458d-b08c-e8213afbb2f9">
@Jagroop2001 do we need to change year to 2024?

**Comment by manyaa1** [comment]
@Jagroop2001 I have raised a PR kindly review it.
Also , please consider changing the tag
