### ISSUE TITLE
`Revamp Readme.md` for Improved Clarity and Consistency

### ISSUE THREAD

**Issue by this-is-yaash** [Jagroop2001/AcmeRockets#27]
The current readme.md **lacks clarity and consistency**, posing challenges for users to **understand the project**. Moreover, the inclusion of images in **varied sizes and positions** creates a visually awkward experience. Proposed enhancements include:

1. **Visual Consistency**: Standardize image sizes and positions for a cohesive and professional appearance.
3. **Setup Documentation**: Rewrite and simplify setup instructions, providing a clear, step-by-step guide for users.

To be precise, these changes aim to deliver a more user-friendly and aesthetically pleasing documentation.

If this issue is valid, then assign me to work on this under **JWOC**

**Comment by Jagroop2001** [comment]
@this-is-yaash , go for it.

**Comment by this-is-yaash** [comment]
@Jagroop2001 
Can you give me some key points about this *Acme Rockets* site
1. What's this site is for?
2. What does this site focuses?
3. Who are the main visitors for this site?

**Comment by Jagroop2001** [comment]
@this-is-yaash , you can take reference from the current readme.md file or run project locally.

**Comment by this-is-yaash** [comment]
yeah
but I kinda got confused 

let me ask you one thing...is this site about *actual rockets*?

**Comment by this-is-yaash** [comment]
This project is not licensed right?

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/pull/51

**Comment by Jagroop2001** [comment]
> This project is not licensed right?

yes
