### ISSUE TITLE
Hover effect and curor pointer for the our rockets part and nav bar

### ISSUE THREAD

**Issue by thesri** [Jagroop2001/AcmeRockets#3]
because all these effects enhances and the look of the website

**Comment by arrx-03** [comment]
Can I contribute to this project (jwoc 24)

**Comment by Jagroop2001** [comment]
Hello, @arrx-03  This issue will be assigned to you as soon as the contribution period begins. However, you can work on this till then.

**Comment by thesri** [comment]
@Jagroop2001 i have commented this issue first and the label for jwoc 🤧ain’t it so that I get assigned?

**Comment by Jagroop2001** [comment]
I apologise to @thesri for missing this. 
Alright, @thesri, you can tackle this problem. @arrx-03, could you kindly make another one that doesn't already exist on the list?

**Comment by thesri** [comment]
i am starting to work on this>? @Jagroop2001

**Comment by Jagroop2001** [comment]
Go ahead @thesri  !!
