### ISSUE TITLE
Footer redesign.

### ISSUE THREAD

**Issue by debuuuu007** [Jagroop2001/AcmeRockets#30]
I would like to redesign the footer into a new one, which will look good and professional as well.
![Screenshot 2024-01-19 153721](https://github.com/Jagroop2001/AcmeRockets/assets/121102183/cf5da713-b7d5-4fb0-9a00-b7e7e2e067c0)

something like this.

**Comment by Jagroop2001** [comment]
go for it @debuuuu007
