### ISSUE TITLE
About us section

### ISSUE THREAD

**Issue by Rishav9911** [Jagroop2001/AcmeRockets#31]
I think an about us section would let the users understand this website a little better as just that small description does not give the exact idea of what exactly is this site for. If you can provide me the description you would like on the site, i can add an attractive about us section to the site and make the site more understanding for the others.
if you like this idea, kindly assign me this issue under JWOC.

**Comment by Jagroop2001** [comment]
@Rishav9911 , you can suggest.

**Comment by Rishav9911** [comment]
sure I can provide some designs and if you do find any suitable we can go with that.

**Comment by Rishav9911** [comment]
hey there according to the website ui i have come up with some designs, does any of the below looks feasible @Jagroop2001 ? 

1.
![Screenshot 2024-01-21 175612](https://github.com/Jagroop2001/AcmeRockets/assets/133174630/90f92f51-ea07-4c7a-92f4-e7562c7c95bc)

2.
![Screenshot 2024-01-21 175241](https://github.com/Jagroop2001/AcmeRockets/assets/133174630/1fd5a36f-a6c2-415a-a549-090a9df995a4)

3.
![Screenshot 2024-01-21 173407](https://github.com/Jagroop2001/AcmeRockets/assets/133174630/c7d804f2-2406-4845-8db5-c5242d781a76)

4.
![Screenshot 2024-01-21 171838](https://github.com/Jagroop2001/AcmeRockets/assets/133174630/c142ad9b-d0aa-4ce9-87bb-08832bff4889)

**Comment by Rishav9911** [comment]
I have applied above changes which works both for dark and light mode and also added about us in navbar, Does it require any other change? kindly review @Jagroop2001 
 
![Screenshot 2024-01-21 194024](https://github.com/Jagroop2001/AcmeRockets/assets/133174630/3a564f16-9ba7-4600-92ed-09bdf246abb1)

![Screenshot 2024-01-21 194014](https://github.com/Jagroop2001/AcmeRockets/assets/133174630/cdbbd52e-44ae-4913-97e7-cd7710bbf0bc)

**Comment by Rishav9911** [comment]
kindly review @Jagroop2001 so that I can commit this change and start working on other issues as well. Thank you.
