### ISSUE TITLE
Redesign the contact us section

### ISSUE THREAD

**Issue by Aadhya-Sharma** [Jagroop2001/AcmeRockets#32]
### Problem

The current contact us section lacks visual appeal.

### Proposed Solution

Revamp the contact us section by enhancing its visual appeal by improving its alignment and color scheme as well as including more related fields.

**Comment by Aadhya-Sharma** [comment]
I would like to work on this issue under JWOC.

**Comment by Jagroop2001** [comment]
@Aadhya-Sharma , 
Go for it !!
