### ISSUE TITLE
Add better Scrollbar 

### ISSUE THREAD

**Issue by itsmeabhishek03** [Jagroop2001/AcmeRockets#33]
Instead of the default scrollbar I can add better and moder scrollbar.

![image](https://github.com/Jagroop2001/AcmeRockets/assets/104294494/b1960594-5fc4-41a1-9330-862ad9db3ee8)
modify these

Please assign this issue to me under JWOC. Thank You.

**Comment by Jagroop2001** [comment]
@itsmeabhishek03 , go for it.

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/pull/36
