### ISSUE TITLE
A "go to top" button

### ISSUE THREAD

**Issue by debuuuu007** [Jagroop2001/AcmeRockets#37]
As i have seen that your website lags a go to top button, so i would like to contribute in it by making such a button.

Thank you.

**Comment by Jagroop2001** [comment]
@debuuuu007 ,
Can you please explain this more.

**Comment by debuuuu007** [comment]
Yes, definitely 

In many website if you visit them and scroll a little, a button appears usually in the right bottom corner. If we click on the button, the page goes up till top.

**Comment by debuuuu007** [comment]
Yess thank you.
