### ISSUE TITLE
 Modifying Dark mode to Light

### ISSUE THREAD

**Issue by shahil-afroz** [Jagroop2001/AcmeRockets#4]
![WhatsApp Image 2024-01-11 at 18 25 12_5722ca10](https://github.com/Jagroop2001/AcmeRockets/assets/137023904/d37a482e-7b17-44b5-9388-09b3fea7c633)

![WhatsApp Image 2024-01-11 at 18 25 12_c0e9a0ee](https://github.com/Jagroop2001/AcmeRockets/assets/137023904/fc3b9ddf-1f12-47d3-a756-593571c6765a)

like this web site we can change the mode....

I am willing to work on this feature, please assign this to me once the coding phase starts (JWOC 24).

**Comment by Jagroop2001** [comment]
Hi @shahil-afroz !!
Dark mode is already implemented. But can add a button that toggle mode of the webpage.

**Comment by shahil-afroz** [comment]
Ok...

**Comment by shahil-afroz** [comment]
So Can I started the coding?

**Comment by Jagroop2001** [comment]
Already assigned @shahil-afroz  !!

**Comment by Surajit0573** [comment]
Hi, @Jagroop2001 , It has been 5 days since this issue was assigned. and the time limit for a medium issue was 3 days...so please re-assign this to me under 2024...I want to work on this issue.

**Comment by Jagroop2001** [comment]
@Surajit0573 , go for it.
