### ISSUE TITLE
Resolve issues in light-mode

### ISSUE THREAD

**Issue by Jagroop2001** [Jagroop2001/AcmeRockets#46]
- Icon that toggle mode is not visible properly in light mode.
- Testimonial slider is not properly visible in light mode.
Here is video for reference : 
https://www.awesomescreenshot.com/video/24256916?key=e788bf5f723f2f32904e0a979c5fe512

**Comment by daksh1210jain** [comment]
i would like to work on this issue
under JWOC

**Comment by vishal2005025** [comment]
I have read the issue and I would like to work on this issue .
please assign it to me under JWOC'2024.

**Comment by Jagroop2001** [comment]
@daksh1210jain , go for it.

**Comment by Jagroop2001** [comment]
@vishal2005025 , you can choose or create different issue.
