### ISSUE TITLE
Need to update README.md as links to code of conduct and MIT License  markdown  files not working

### ISSUE THREAD

**Issue by manyaa1** [Jagroop2001/AcmeRockets#50]
<img width="801" alt="image" src="https://github.com/Jagroop2001/AcmeRockets/assets/134845162/f7188df3-98c0-4ef9-885e-b06a2be26860">
<img width="897" alt="image" src="https://github.com/Jagroop2001/AcmeRockets/assets/134845162/2bf377f6-e4d3-4858-8f4c-d189de78db35">
kindly assign me this issue under JWOC'24.

**Comment by Jagroop2001** [comment]
@manyaa1 , go for it
