### ISSUE TITLE
Add hover feature on all the 3 rocket variants available

### ISSUE THREAD

**Issue by daksh1210jain** [Jagroop2001/AcmeRockets#54]
I want t add feature that whenever you hover on 3 rockets available the photo gets zoomed

**Comment by Jagroop2001** [comment]
@daksh1210jain , go for it.

**Comment by daksh1210jain** [comment]
sir when i cloned the project the following the user interface 
![image](https://github.com/Jagroop2001/AcmeRockets/assets/137384322/d5884e6a-8c6e-4df0-9ce5-fac86aca7c12)
kindly resolve the error so that i can work on the correct code

**Comment by Jagroop2001** [comment]
@daksh1210jain  run npm run tailwind in the terminal as well.

**Comment by daksh1210jain** [comment]
sir i have made changes to perform the necssary task kindly have a look and accept my PR
