### ISSUE TITLE
Add Github, linkedin, instagram icons at bootom

### ISSUE THREAD

**Issue by vishapraj** [Jagroop2001/AcmeRockets#56]

**Comment by vishapraj** [comment]
@Jagroop2001 pls assign me this issue under "JWOC"

**Comment by Jagroop2001** [comment]
@vishapraj , go  for it.

**Comment by Jagroop2001** [comment]
@vishapraj Please reply if you are still working. I will wait until 12 hours, otherwise I will assign this to @vishal2005025.

**Comment by Hacxmr** [comment]
Hey ! @Jagroop2001 If the issue has not yet been resolved. I am interested in contributing to this

**Comment by Jagroop2001** [comment]
@Hacxmr , go for it.
