### ISSUE TITLE
Redesign `Contact Us` 

### ISSUE THREAD

**Issue by this-is-yaash** [Jagroop2001/AcmeRockets#57]
Current **Contact Us** module looks odd & doesn't match the site UI.
![image](https://github.com/Jagroop2001/AcmeRockets/assets/84762257/24d09369-a108-421a-b3df-8dcaefca47da)
I propose to,
- Slightly reduce the size of text view box to match site scaling.
- Placeholder text opacity need to reduced (slightly)
- Adding **Email** text view box at the start
- Upon clicking on the text view box, it has border in blue color which needs to be changed to match the site UI.
- Slight reword on the **Submit** button.

If this issue is valid, then assign me to work on this under **JWOC**

**Comment by Jagroop2001** [comment]
@this-is-yaash , it's already updated. Please pull updated code from master.
![Screenshot from 2024-01-26 11-54-32](https://github.com/Jagroop2001/AcmeRockets/assets/99062463/1c507eb7-2592-499d-80db-f486f2abc0db)
