### ISSUE TITLE
Scrollbar can be customized to enhance overall design of the website.

### ISSUE THREAD

**Issue by vipul-dixit-2004** [Jagroop2001/AcmeRockets#6]

**Comment by Jagroop2001** [comment]
@vipul-dixit-2004  !!
You should start addressing this  feature.

**Comment by rahat2134** [comment]
@Jagroop2001 assign me this JWOC

**Comment by Sruti-sahini** [comment]
Hello @vipul-dixit-2004 
I have a good hold in web development 
Could you please assign me this issue after the coding periods starts?
I am from JWoC'24

**Comment by Jagroop2001** [comment]
Hi @Sruti-sahini  !!
This issue is assiged to @vipul-dixit-2004 , 
You can either create or select unassigned issue.

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/pull/9

**Comment by Jagroop2001** [comment]
https://github.com/Jagroop2001/AcmeRockets/pull/9
