### ISSUE TITLE
Add : Light & Dark Mode 

### ISSUE THREAD

**Issue by Surajit0573** [Jagroop2001/AcmeRockets#60]
Currently there is no light and dark mode. 

![image](https://github.com/Jagroop2001/AcmeRockets/assets/111490250/7b4a18a6-9b3f-4503-b836-9ca0ba139610)

I want to add a toggle button for toggle between light and dark mode.
Please assign me under JWOC 2024, if approved.

**Comment by Jagroop2001** [comment]
It's already available, please take pull from master.

**Comment by Surajit0573** [comment]
@Jagroop2001 why it's not visible in deployment in this https://64bcf6b874de0805368c53b9--timely-flan-114f94.netlify.app/ you provide.

**Comment by Jagroop2001** [comment]
I didn't updated yet because here everyday new changes are merged
