### ISSUE TITLE
Improve Header 

### ISSUE THREAD

**Issue by Jagroop2001** [Jagroop2001/AcmeRockets#63]
Currently header is looking like this : 
![Acme-Rockets (2)](https://github.com/Jagroop2001/AcmeRockets/assets/99062463/4eada673-efb6-4667-9f3a-83c44dd2321d)

I want to make it align in a single line

**Comment by vishal2005025** [comment]
I would like to work on this issue .
Please assign it to me under JWOC'2024.

**Comment by Jagroop2001** [comment]
@vishal2005025 , go for it.
