### ISSUE TITLE
Change color in the slider

### ISSUE THREAD

**Issue by Jagroop2001** [Jagroop2001/AcmeRockets#64]
Change color in the slider
![Acme-Rockets (3)](https://github.com/Jagroop2001/AcmeRockets/assets/99062463/678f6063-9175-400a-a024-387392ae61ec)

I want to change : 
-  red color to white  ( Dark Mode)
-  red color to black ( Light Mode)

**Comment by vishal2005025** [comment]
I Would like to work on this issue.
Please assign it to me under JWOC'2024.

**Comment by vishal2005025** [comment]
sir , firstly I want to work on this .
please assign it to me.

**Comment by Jagroop2001** [comment]
@vishal2005025 , go for ti

**Comment by vishal2005025** [comment]
thank you!
