### ISSUE TITLE
Rewrite the Readme.md file of AcmeRockets projects.

### ISSUE THREAD

**Issue by Jagroop2001** [Jagroop2001/AcmeRockets#7]
**Rewrite the readme.md file for AcmeRockets projects.**
- Add project details.
- Include a demo (screenshot, video, or gif) 
- Include contribution guidelines. 
- Include other relevant items, but please indicate them in the comments.

**Comment by rahat2134** [comment]
@Jagroop2001 assign this to me under JWOC.

**Comment by rahat2134** [comment]
when coding phase starts.

**Comment by Jagroop2001** [comment]
Hi @rahat2134  !!
You can start on this feature.

**Comment by rahat2134** [comment]
but it should be done when coding phase starts right?

**Comment by Jagroop2001** [comment]
> @Jagroop2001 but it should be done when coding phase starts right? let the coding phase1 starts.

Yes @rahat2134 , it will be starting tomorrow.  You can either start before or tomorrow onwards but I will officially counting this tomorrow.

**Comment by rahat2134** [comment]
okay.

**Comment by rahat2134** [comment]
@Jagroop2001 your linkedIn id as i need to connect u.(mine is https://www.linkedin.com/in/rahat-a59686248/)

**Comment by Jagroop2001** [comment]
> @Jagroop2001 your linkedIn id as i need to connect u.(mine is https://www.linkedin.com/in/rahat-a59686248/)

Here it is : https://www.linkedin.com/in/jagroop-singh-3a2a401b4/

**Comment by rahat2134** [comment]
@Jagroop2001  i have three days to complete this task right? 15,16,17
