### ISSUE TITLE
Upgrade this project to ReactJS.

### ISSUE THREAD

**Issue by Jagroop2001** [Jagroop2001/AcmeRockets#8]
**Upgrade this project to ReactJS :** 
- Upgrade this by using Webpack or Vite.
-  Add Eslinter to this project.
-  Organize the code into Components.

**Comment by Abhishek-465** [comment]
I want to work on this issue. I can convert this project into a React project and implement the organisation of code components.
Kindly assign me.
Contributing under JWOC

**Comment by Abhishek-465** [comment]
@Jagroop2001 
I want to work on this issue. I can convert this project into a React project and implement the organisation of code components.
Kindly assign me.
Contributing under JWOC

**Comment by Jagroop2001** [comment]
Go ahead @Abhishek-465  !!

**Comment by Abhishek-465** [comment]
No i am not working on this.
Thank you

**Comment by this-is-yaash** [comment]
Assign me to work on this issue under JWOC

I'll work on to,
1. Change this project to ReactJs.
2. Organize source code.
3. Use EsLinter to make code readable.

**Comment by Jagroop2001** [comment]
@this-is-yaash ,
go for it.
Also when completed create a PR against `master_react` branch

**Comment by this-is-yaash** [comment]
Got it👍

**Comment by yuvrajgohil24** [comment]
@Jagroop2001 
If @this-is-yaash is not working on this issue then you can assign this to me.

**Comment by Syed0206** [comment]
Please Assign this  issue to me. Iam interested to work on this issue.

**Comment by warmachine028** [comment]
Assign me this issue under WOC

**Comment by Jagroop2001** [comment]
@warmachine028 , go for it.

**Comment by warmachine028** [comment]
I have added a PR #117, please look into it
