### ISSUE TITLE
Add light and dark mode option

### ISSUE THREAD

**Issue by Sanglap-Halder** [Jagroop2001/AcmeRockets#81]
Assign me this issue under JWoC 2024

**Comment by kaif969** [comment]
please assign it to me under JWOC'2024.

**Comment by Jagroop2001** [comment]
@kaif969 , this functionality is already implemented.
Please choose different issue or create new one.

**Comment by Sanglap-Halder** [comment]
@Jagroop2001 but where is the functionality?

**Comment by Jagroop2001** [comment]
@Sanglap-Halder , go for it

**Comment by Sanglap-Halder** [comment]
The page that is showing when I open it through the link given in GitHub
and the page that is showing when I open it on live server after cloning on
my local machine are completely different. Why is this happening?

**Comment by Jagroop2001** [comment]
Make sure to pull from master and run npm run tailwind as well.
