### ISSUE TITLE
STYLE improvement in footer

### ISSUE THREAD

**Issue by AftabMankapure** [Jagroop2001/AcmeRockets#83]
improvement in footer 

Current footer
![footer](https://github.com/Jagroop2001/AcmeRockets/assets/125949765/017edc15-a02f-4110-b185-963206bb6c86)

We can divide footer in 3 part
1. Contact  us
2. link
3. Social Share

**Comment by AftabMankapure** [comment]
New footer  

![newFoot](https://github.com/Jagroop2001/AcmeRockets/assets/125949765/b058fafc-ec69-4997-84c4-98666505a7d5)

**Comment by Jagroop2001** [comment]
@AftabMankapure , go for it.
