### ISSUE TITLE
Correct Navbar functionality

### ISSUE THREAD

**Issue by Jagroop2001** [Jagroop2001/AcmeRockets#89]
Currently, navbar functionality is distorted.Want to make it correct.

**Comment by SohanRC** [comment]
Assign me this issue under JWOC 2024

**Comment by Sneha123-zudo** [comment]
Please assign me this issue under JWOC

**Comment by SohanRC** [comment]
> Assign me this issue under JWOC 2024

Please assign me this issue under JWOC 2024
