### ISSUE TITLE
[feat] : Add some nice animation at hero image and hovering at cards

### ISSUE THREAD

**Issue by rishovchakraborty** [Jagroop2001/AcmeRockets#95]
**Description of the issue**
the static hero image and cards making the website unattractive. Here i've add some photos of the feature.

<img width="710" alt="Screenshot 2024-02-13 092624" src="https://github.com/Jagroop2001/AcmeRockets/assets/116090136/53ac7898-bf8a-4a89-be3f-b127cb17306f">
<img width="721" alt="Screenshot 2024-02-13 092658" src="https://github.com/Jagroop2001/AcmeRockets/assets/116090136/e31e9b50-86f0-4a17-a9cf-3861764fe51b">

**Comment by Jagroop2001** [comment]
@rishovchakraborty , go for it.
